const types = {
  GET_CURRENCIES_SUCCESS: 'GET_CURRENCIES_SUCCESS',
  GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
  GET_RATES_REQUEST: 'GET_RATES_REQUEST',
  GET_RATES_SUCCESS: 'GET_RATES_SUCCESS',
  GET_RATES_ERROR: 'GET_RATES_ERROR',
};

export default types;